cartesian_limits:
  max_trans_vel: 0.5   # Slower translational speed
  max_trans_acc: 1.0   # Reduced acceleration for smoother starts
  max_trans_dec: -2.5  # Softer deceleration for controlled stops
  max_rot_vel: 0.78    # Slower rotational speed (approximately 45 degrees per second)
